2024-07-31 14:59:24,859 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:24,861 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:24,864 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:24,864 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:24,864 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:24,864 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:25,326 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:25,326 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:25,329 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:25,329 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:25,330 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:25,330 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:43,162 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:40]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 26, in send_email
    ip_address = socket.gethostbyname(current_app.config['MAIL_SERVER'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 14:59:43,162 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:40]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 26, in send_email
    ip_address = socket.gethostbyname(current_app.config['MAIL_SERVER'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 14:59:43,935 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:43,935 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:43,950 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:43,950 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 14:59:43,951 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 14:59:43,951 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:00:04,836 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:40]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 26, in send_email
    ip_address = socket.gethostbyname(current_app.config['MAIL_SERVER'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 15:00:04,836 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:40]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 26, in send_email
    ip_address = socket.gethostbyname(current_app.config['MAIL_SERVER'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 15:02:57,307 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:40]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 26, in send_email
    ip_address = socket.gethostbyname(current_app.config['MAIL_SERVER'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 15:02:57,307 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:40]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 26, in send_email
    ip_address = socket.gethostbyname(current_app.config['MAIL_SERVER'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 15:04:08,210 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:04:08,211 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:04:08,213 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:04:08,213 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:04:08,214 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:04:08,214 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:04:12,959 ERROR: Failed to send email to saito_kouki@simmon.jp: [Errno 11001] getaddrinfo failed [in c:\Users\2880\Desktop\forms\froms\app\services\email_service.py:39]
Traceback (most recent call last):
  File "c:\Users\2880\Desktop\forms\froms\app\services\email_service.py", line 28, in send_email
    with smtplib.SMTP(smtp_server, current_app.config['MAIL_PORT']) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2880\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2880\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2880\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2880\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 828, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2880\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
2024-07-31 15:04:13,805 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:04:13,805 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:04:13,808 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:04:13,808 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:04:13,808 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:04:13,808 INFO: Mail configuration: SERVER=stmp.simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:05:51,081 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:05:51,081 INFO: Mail configuration: SERVER=simmon.jp# 使用するメールサービスのSMTPサーバー, PORT=587, USE_TLS=True, USE_SSL=False [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:63]
2024-07-31 15:05:51,084 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
2024-07-31 15:05:51,084 INFO: Survey startup [in c:\Users\2880\Desktop\forms\froms\app\__init__.py:60]
